import { NextResponse } from 'next/server';
import { generateAiPortfolio, saveStudentPortfolio } from '@/lib/services/portfolio.service';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { fullName, email, location, skills, completedCourses, education } = body;

    if (!fullName || !email) {
      return NextResponse.json({ error: 'Name and email are required to build portfolio' }, { status: 400 });
    }

    const portfolio = await generateAiPortfolio({
      fullName,
      email,
      location,
      skills,
      completedCourses,
      education,
    });

    await saveStudentPortfolio(portfolio);

    return NextResponse.json({
      success: true,
      portfolio,
      message: 'Portfolio successfully generated by GlobeSkill AI Career Architect!',
    });
  } catch (error: unknown) {
    const errorMsg = error instanceof Error ? error.message : 'Portfolio generation error';
    return NextResponse.json({ error: errorMsg }, { status: 500 });
  }
}
